#!/bin/bash

APP="$(pwd)/.build/bundle"
SCRIPT="$APP/main.js"
PID="$APP/good.pid"
LOG="$APP/good.log"

# exports
export PORT=6000
export MONGO_URL="mongodb://localhost:27017/good"
export ROOT_URL="http://good.yasaricli.com"
export DISABLE_WEBSOCKETS=true

#remove .build
rm -rf .build

# meteor build  and extract
meteor build .build --server "$ROOT_URL:$PORT"
cd .build
tar -xvf good.tar.gz


# npm install dep
cd bundle/programs/server
npm install

forever stop $SCRIPT
forever start -p $APP --pidFile $PID -l $LOG -a -d $SCRIPT
